const MATERIALS_BASE = [
  { id: "mat-01", name: "ALCOHOL" },
  { id: "mat-02", name: "PAÑALES" },
  { id: "mat-03", name: "GUANTES ESTERILES" },
  { id: "mat-04", name: "GUANTES NO ESTERILES" },
  { id: "mat-05", name: "EQUIPO PARA BOMBA" },
  { id: "mat-06", name: "NORMOGOTERO" },
  { id: "mat-07", name: "MICROGOTERO" },
  { id: "mat-08", name: "LLAVE DE TRES VIAS" },
  { id: "mat-09", name: "EQUIPO PARA TRASFUSION SIMPLE" },
  { id: "mat-10", name: "PUNZOCAT NO." },
  { id: "mat-11", name: "JERINGAS 3ML" },
  { id: "mat-12", name: "JERINGAS 5ML" },
  { id: "mat-13", name: "JERINGAS 10ML" },
  { id: "mat-14", name: "JERINGAS 20ML" },
  { id: "mat-15", name: "JERINGAS INSULINA" },
  { id: "mat-16", name: "FIJACION DE SONDA FOLEY" },
  { id: "mat-17", name: "DETERGENTE ENZIMATICO" },
  { id: "mat-18", name: "CISTOFLOW" },
  { id: "mat-19", name: "APOSITO" },
  { id: "mat-20", name: "GASAS NO ESTERILES" },
  { id: "mat-21", name: "TEGADERM" },
  { id: "mat-22", name: "PUNTAS NASALES" },
  { id: "mat-23", name: "CINTA UMBILICAL" },
  { id: "mat-24", name: "VENDAS DE NUM.5/10/15/30" },
  { id: "mat-25", name: "BAÑO SECO" },
  { id: "mat-26", name: "ELECTRODOS" },
  { id: "mat-27", name: "AGUJA AMARILLA O NEGRA" },
  { id: "mat-28", name: "SONDA FOLEY FR:" },
  { id: "mat-29", name: "S. NELATON FR:" },
  { id: "mat-30", name: "BATAS NO ESTERIL" },
  { id: "mat-31", name: "RASTRILLOS" },
  { id: "mat-32", name: "CANULA DE GUEDEL NO:" },
];

const SERVICES_BASE = [
  { id: "serv-01", name: "4 PISO MEDICINA INTERNA" },
  { id: "serv-02", name: "3 PISO CIRUGIA GENERAL" },
  { id: "serv-03", name: "3 PISO CIRUGIA GENERAL (NOCTURNO A)" },
  { id: "serv-04", name: "PEDIATRIA" },
  { id: "serv-05", name: "GINECOLOGIA" },
  { id: "serv-07", name: "UCEN" },
  { id: "serv-08", name: "UCI" },
  { id: "serv-09", name: "UCIN" },
  { id: "serv-10", name: "UTIP" },
  { id: "serv-12", name: "QUIROFANO CENTRAL" },
  { id: "serv-13", name: "TOCOCIRUGIA" },
  { id: "serv-14", name: "CIRUGIA AMBULATORIA" },
  { id: "serv-15", name: "URG. ADULTO" },
  { id: "serv-16", name: "URG. CURACIONES" },
  { id: "serv-17", name: "URG. PEDIATRIA" },
];

const TEMPLATES = [
  {
    id: "temp-01",
    service_id: "serv-01",
    items: [
      { id: "rel-01", material_id: "mat-01", stock: null },
      { id: "rel-02", material_id: "mat-02", stock: 40 },
      { id: "rel-03", material_id: "mat-03", stock: 100 },
      { id: "rel-04", material_id: "mat-04", stock: 100 },
      { id: "rel-05", material_id: "mat-05", stock: null },
      { id: "rel-06", material_id: "mat-06", stock: 40 },
      { id: "rel-07", material_id: "mat-07", stock: 6 },
      { id: "rel-08", material_id: "mat-08", stock: 6 },
      { id: "rel-09", material_id: "mat-09", stock: 5 },
      { id: "rel-10", material_id: "mat-10", stock: 10 },
      { id: "rel-11", material_id: "mat-11", stock: 30 },
      { id: "rel-12", material_id: "mat-12", stock: 30 },
      { id: "rel-13", material_id: "mat-13", stock: 60 },
      { id: "rel-14", material_id: "mat-14", stock: 60 },
      { id: "rel-15", material_id: "mat-15", stock: 30 },
      { id: "rel-16", material_id: "mat-16", stock: 2 },
      { id: "rel-17", material_id: "mat-17", stock: 1 },
      { id: "rel-18", material_id: "mat-30", stock: 10 },
      { id: "rel-19", material_id: "mat-19", stock: 1 },
      { id: "rel-20", material_id: "mat-20", stock: 1 },
      { id: "rel-21", material_id: "mat-21", stock: 10 },
      { id: "rel-22", material_id: "mat-31", stock: 6 },
      { id: "rel-23", material_id: "mat-32", stock: 2 },
      { id: "rel-24", material_id: "mat-23", stock: 20 },
      { id: "rel-25", material_id: "mat-24", stock: 12 },
      { id: "rel-26", material_id: "mat-25", stock: 15 },
      { id: "rel-27", material_id: "mat-26", stock: 20 },
      { id: "rel-28", material_id: "mat-27", stock: 100 },
      { id: "rel-29", material_id: "mat-28", stock: 5 },
      { id: "rel-30", material_id: "mat-29", stock: 5 },
    ],
  },
  {
    id: "temp-02",
    service_id: "serv-02",
    items: [
      { id: "rel-01", material_id: "mat-01", stock: null },
      { id: "rel-02", material_id: "mat-02", stock: 40 },
      { id: "rel-03", material_id: "mat-03", stock: 100 },
      { id: "rel-04", material_id: "mat-04", stock: 100 },
      { id: "rel-05", material_id: "mat-05", stock: null },
      { id: "rel-06", material_id: "mat-06", stock: 40 },
      { id: "rel-07", material_id: "mat-07", stock: 6 },
      { id: "rel-08", material_id: "mat-08", stock: 6 },
      { id: "rel-09", material_id: "mat-09", stock: 5 },
      { id: "rel-10", material_id: "mat-10", stock: 10 },
      { id: "rel-11", material_id: "mat-11", stock: 30 },
      { id: "rel-12", material_id: "mat-12", stock: 30 },
      { id: "rel-13", material_id: "mat-13", stock: 60 },
      { id: "rel-14", material_id: "mat-14", stock: 60 },
      { id: "rel-15", material_id: "mat-15", stock: 30 },
      { id: "rel-16", material_id: "mat-16", stock: 2 },
      { id: "rel-17", material_id: "mat-17", stock: 1 },
      { id: "rel-18", material_id: "mat-18", stock: 6 },
      { id: "rel-19", material_id: "mat-19", stock: 1 },
      { id: "rel-20", material_id: "mat-20", stock: 1 },
      { id: "rel-21", material_id: "mat-21", stock: 10 },
      { id: "rel-22", material_id: "mat-22", stock: 6 },
      { id: "rel-23", material_id: "mat-18", stock: 5 },
      { id: "rel-24", material_id: "mat-23", stock: 20 },
      { id: "rel-25", material_id: "mat-24", stock: 12 },
      { id: "rel-26", material_id: "mat-25", stock: 15 },
      { id: "rel-27", material_id: "mat-26", stock: 20 },
      { id: "rel-28", material_id: "mat-27", stock: 100 },
      { id: "rel-29", material_id: "mat-28", stock: 5 },
      { id: "rel-30", material_id: "mat-29", stock: 5 },
    ],
  },
];

const STATUSES_BASE = [
  { id: "stat-01", name: "Pendiente" },
  { id: "stat-02", name: "En Preparación" },
  { id: "stat-03", name: "En Camino" },
  { id: "stat-04", name: "Entregado" },
  { id: "stat-05", name: "Cancelado" },
];

const SHIFTS_BASE = [
  { id: "shift-01", name: "Matutino" },
  { id: "shift-02", name: "Vespertino" },
  { id: "shift-03", name: "Nocturno" },
];

module.exports = {
  MATERIALS_BASE,
  SERVICES_BASE,
  TEMPLATES,
  STATUSES_BASE,
  SHIFTS_BASE,
};
